name: Setup Java
description: Set up Zulu JDK from .java-version

runs:
  using: composite
  steps:
    - name: Setup JDK
      uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5
      with:
        java-version-file: .java-version
        distribution: zulu
