---
comments:
  active: false

naming:
  FunctionNameMaxLength:
    excludes: [ '**/test/**', '**/*Test/**' ]

potential-bugs:
  UnnamedParameterUse:
    active: false

style:
  UnnecessaryApply:
    active: false
  MultilineRawStringIndentation:
    active: false
  RedundantVisibilityModifier:
    active: false
  ReturnCount:
    max: 3
