---
comments:
  active: false

complexity:
  LabeledExpression:
    active: false

naming:
  BooleanPropertyNaming:
    allowedPattern: "^(is|has|are|can|allow)"
  FunctionNameMaxLength:
    excludes: [ '**/test/**', '**/*Test/**' ]

potential-bugs:
  UnnamedParameterUse:
    active: false

style:
  CascadingCallWrapping:
    # clashes with ktfmt
    active: false
  UnnecessaryApply:
    active: false
  MultilineRawStringIndentation:
    active: false
  RedundantVisibilityModifier:
    active: false
  ReturnCount:
    max: 3
