name: CI

on:
  push:
    branches:
      - '*'

env:
  ORG_GRADLE_PROJECT_RELEASE_SIGNING_ENABLED: false

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 11

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          gradle-version: wrapper

      - name: Check
        run: ./gradlew check

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3
