name: Submit Dependency Graph

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 19
          distribution: "zulu"

      - name: Add permissions
        run: chmod +x ./gradlew

      - name: Submit dependencies
        uses: gradle/actions/dependency-submission@v3
