name: Main

on:
  push:
    branches: [ "main" ]

env:
  ORG_GRADLE_PROJECT_RELEASE_SIGNING_ENABLED: false

permissions:
  contents: write
  checks: write

concurrency:
  group: 'ci-${{ github.event.merge_group.head_ref || github.head_ref }}-${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  main-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          generate-job-summary: false
          gradle-version: wrapper

      - name: Check
        run: ./gradlew check

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: check-reports
          path: |
            ./*/build/reports
            ./build/reports
          if-no-files-found: warn

      - name: Publish test reports
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: "**/build/test-results/*/TEST-*.xml"
